# steph : charge la config bash de l'utilisateur puis ajoute les marqueurs de commande.
[[ -f ~/.bashrc ]] && source ~/.bashrc
__steph_b64() { printf '%s' "$1" | base64 -w0; }
__steph_in_cmd=0
__steph_preexec() {
  [[ $__steph_in_cmd == 1 ]] && return
  [[ -n "$COMP_LINE" ]] && return
  [[ "$BASH_COMMAND" == __steph_precmd* ]] && return
  __steph_in_cmd=1
  local c; c=$(HISTTIMEFORMAT= history 1 | sed -E 's/^ *[0-9]+\*? *//')
  printf '\e]6973;C;%s\a' "$(__steph_b64 "$c")"
}
__steph_precmd() {
  local ret=$?
  printf '\e]6973;D;%s;%s\a' "$ret" "$(__steph_b64 "$PWD")"
  __steph_in_cmd=0
}
PROMPT_COMMAND="__steph_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
trap '__steph_preexec' DEBUG
q() { steph ask --once -- "$@"; }
